INSERT INTO categorie(categoriePlante) VALUES
('Rosacées'),
('Liliacées'),
('Monocotylédones'),
('Astéracées'),
('Oléacées'),
('Lamiacées'),
('Nyctaginacées'),
('Amaranthacées'),
('Apiacées'),
('Tropaeolacées'),
('Fabacées'),
('Asteracées'),
('Convolvulacées'),
('Linacées'),
('Solanacées'),
('Amaryllidacées'),
('Papaveracées'),
('Paeoniacées');


INSERT INTO especeDePlante(nom, description, humidite, temperature, luminosite, periodeFloraisonDebut, periodeFloraisonFin, id_categorie)
VALUES
('Rose', 'Rose ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 10,  -5, 96, 'Août', 'Septembre', 1),
('Tulipe', 'Tulipe ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 13,  -4, 93, 'Mai', 'Juin', 2),
('Orchidée', 'Orchidée ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 16,  -2, 90, 'Juin', 'Août', 3),
('Tournesol', 'Tournesol ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 19,  -1, 87, 'Juillet', 'Novembre', 4),
('Lys', 'Lys ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 21,  0, 84, 'Octobre', 'Juin', 2),
('Muguet', 'Muguet ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 24, 1, 81, 'Août', 'Juillet', 2),
('Lilas', 'Lilas ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 27, 2, 78, 'Avril', 'Décembre', 5),
('Joncquille', 'Joncquille ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 30, 3, 75, 'Avril', 'Octobre', 16),
('Coquelicot', 'Coquelicot ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 33, 4, 72, 'Mai', 'Avril', 17),
('Pivoine', 'Pivoine ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 36, 5, 69, 'Août', 'Décembre', 18),
('Jasmin', 'Jasmin ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 39, 6, 66, 'Mars', 'Décembre', 5),
('Lavande', 'Lavande ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 42, 7, 63, 'Octobre', 'Février', 6),
('Morelle noire', 'Morelle noire ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 45, 8, 60, 'Août', 'Mai', 6),
('Bougainvillea', 'Bougainvillea ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 48, 9, 57, 'Mars', 'Juin', 7),
('Amarante', 'Amarante ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 51, 10, 54, 'Mars', 'Décembre', 8),
('Ammi', 'Ammi ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 54, 11, 51, 'Mai', 'Juillet', 9),
('Belle-de-nuit', 'Belle-de-nuit ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 57, 12, 48, 'Octobre', 'Juillet', 7),
('Dahlia', 'Dahlia ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 60, 13, 45, 'Mai', 'Avril', 4),
('Capucine', 'Capucine ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 63, 14, 42, 'Février', 'Mai', 10),
('Rose trémière', 'Rose trémière ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 66, 15, 39, 'Septembre', 'Février', 11),
('Pois de senteur', 'Pois de senteur ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 69, 16, 36, 'Août', 'Juillet', 12),
('Souci officinal', 'Souci officinal ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 72, 17, 33, 'Mai', 'Mai', 13),
('Ipomé', 'Ipomé ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 75, 17, 30, 'Août', 'Juin', 14),
('Lin cultivé', 'Lin cultivé ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 78, 18, 27, 'Mars', 'Juillet', 15),
('Calibrachoa', 'Calibrchoa ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 81, 19, 24, 'Juillet', 'Mars', 16),
('Ageratum', 'Ageratum ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.',84, 20, 21, 'Mai', 'Mai', 4),
('Liseron', 'Liseron ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 87, 21, 19, 'Mai', 'Juin', 14),
('Gomphrena', 'Gomphrena ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 90, 22, 16, 'Mai', 'Avril', 8),
('Nepeta', 'Nepeta ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 93, 23, 13, 'Juin', 'Août', 6),
('Chrysanthème', 'Chrysanthème ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo.', 96, 24, 10, 'Février', 'Juillet', 4);
